-- ---------------------------------------------------------------
-- Eat On — seed data.
--
-- GENERATED FILE — do not edit by hand.
-- Regenerate with:  npm run seed:sql
--
-- Import AFTER schema.sql. Safe to re-run: every insert upserts, so
-- re-importing refreshes the menu without touching orders or staff.
-- ---------------------------------------------------------------

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Categories
INSERT INTO categories (id, name, description, emoji, image_id, display_order, is_published) VALUES ('beef-burgers', 'Beef Burgers', 'Freshly ground meat patties and nicely seasoned meat.', '🍔', NULL, 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), display_order=VALUES(display_order);
INSERT INTO categories (id, name, description, emoji, image_id, display_order, is_published) VALUES ('chicken-burgers', 'Chicken Burgers', 'Freshly ground meat patties and nicely battered meat.', '🍗', NULL, 2, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), display_order=VALUES(display_order);
INSERT INTO categories (id, name, description, emoji, image_id, display_order, is_published) VALUES ('club-sandwich', 'Club Sandwich', 'All come with fresh vegetables and nicely seasoned meat.', '🥪', NULL, 3, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), display_order=VALUES(display_order);
INSERT INTO categories (id, name, description, emoji, image_id, display_order, is_published) VALUES ('cheesy-rascal', 'Cheesy Rascal', 'Give kick to your meal.', '🧀', NULL, 4, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), display_order=VALUES(display_order);
INSERT INTO categories (id, name, description, emoji, image_id, display_order, is_published) VALUES ('add-ons', 'Add Ons', NULL, '🍟', NULL, 5, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), display_order=VALUES(display_order);
INSERT INTO categories (id, name, description, emoji, image_id, display_order, is_published) VALUES ('kids-meal', 'Kids Meal', NULL, '🧒', NULL, 6, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), display_order=VALUES(display_order);
INSERT INTO categories (id, name, description, emoji, image_id, display_order, is_published) VALUES ('beverages', 'Beverages', NULL, '🥤', NULL, 7, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), display_order=VALUES(display_order);

-- Option groups
INSERT INTO modifier_groups (id, name, min_select, max_select) VALUES ('sauceChoice', 'Choose your sauce', 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), min_select=VALUES(min_select), max_select=VALUES(max_select);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('sauceChoice', 'ketchup', 'Ketchup', 0.00, 1, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('sauceChoice', 'chilli', 'Chilli', 0.00, 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('sauceChoice', 'algerian', 'Algerian Sauce', 0.00, 1, 2) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('sauceChoice', 'mayonnaise', 'Mayonnaise', 0.00, 1, 3) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_groups (id, name, min_select, max_select) VALUES ('crispySauce', 'Choose your sauce', 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), min_select=VALUES(min_select), max_select=VALUES(max_select);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('crispySauce', 'chilli', 'Chilli Sauce', 0.00, 1, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('crispySauce', 'mayonnaise', 'Mayonnaise', 0.00, 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_groups (id, name, min_select, max_select) VALUES ('mealDrink', 'Meal drink — if you are making it a meal', 0, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), min_select=VALUES(min_select), max_select=VALUES(max_select);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('mealDrink', 'coke', 'Coca-Cola', 0.00, 1, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('mealDrink', 'diet-coke', 'Diet Coke', 0.00, 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('mealDrink', 'pepsi', 'Pepsi', 0.00, 1, 2) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('mealDrink', 'fanta', 'Fanta', 0.00, 1, 3) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('mealDrink', '7up', '7up', 0.00, 1, 4) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('mealDrink', 'water', 'Water', 0.00, 1, 5) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('mealDrink', 'juice', 'Orange Juice', 0.00, 1, 6) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_groups (id, name, min_select, max_select) VALUES ('extraDips', 'Add dips & peri salt', 0, 4) ON DUPLICATE KEY UPDATE name=VALUES(name), min_select=VALUES(min_select), max_select=VALUES(max_select);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('extraDips', 'peri-salt', 'Peri Salt', 0.50, 1, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('extraDips', 'ketchup-dip', 'Ketchup Dip', 0.50, 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('extraDips', 'chilli-dip', 'Chilli Dip', 0.50, 1, 2) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('extraDips', 'mayo-dip', 'Mayonnaise Dip', 0.50, 1, 3) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_groups (id, name, min_select, max_select) VALUES ('dipType', 'Which dip?', 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), min_select=VALUES(min_select), max_select=VALUES(max_select);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('dipType', 'peri-salt', 'Peri Salt', 0.00, 1, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('dipType', 'ketchup', 'Ketchup', 0.00, 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('dipType', 'chilli', 'Chilli', 0.00, 1, 2) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('dipType', 'mayonnaise', 'Mayonnaise', 0.00, 1, 3) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_groups (id, name, min_select, max_select) VALUES ('softDrinkChoice', 'Which drink?', 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), min_select=VALUES(min_select), max_select=VALUES(max_select);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('softDrinkChoice', 'coke', 'Coca-Cola', 0.00, 1, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('softDrinkChoice', 'diet-coke', 'Diet Coke', 0.00, 1, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('softDrinkChoice', 'pepsi', 'Pepsi', 0.00, 1, 2) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('softDrinkChoice', 'fanta', 'Fanta', 0.00, 1, 3) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);
INSERT INTO modifier_options (group_id, option_key, name, price, is_available, display_order) VALUES ('softDrinkChoice', '7up', '7up', 0.00, 1, 4) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), display_order=VALUES(display_order);

-- Items, sizes and option-group links
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('holy-smash', 'beef-burgers', 'Holy Smash', 'Marinated organic Angus beef patty topped with caramelised onions, lettuce, cheese and your choice of sauce, served in a freshly toasted brioche bun.', '🍔', NULL, 1, 1, 0, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('holy-smash', 'single', 'On its own', 6.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('holy-smash', 'meal', 'Make it a meal', 9.48, 'Adds fries and a drink (+£2.49)', 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('holy-smash', 'sauceChoice', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('holy-smash', 'mealDrink', 1) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('holy-smash', 'extraDips', 2) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('bbq-royale', 'beef-burgers', 'BBQ Royale', 'Marinated organic Angus beef patty with a hint of BBQ sauce, topped with caramelised onions, lettuce and cheese, served with your choice of sauce in a freshly toasted brioche bun.', '🍔', NULL, 0, 1, 1, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('bbq-royale', 'single', 'On its own', 6.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('bbq-royale', 'meal', 'Make it a meal', 9.48, 'Adds fries and a drink (+£2.49)', 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('bbq-royale', 'sauceChoice', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('bbq-royale', 'mealDrink', 1) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('bbq-royale', 'extraDips', 2) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('chick-n-bun', 'chicken-burgers', 'Chick N'' Bun', 'Battered chicken minced patty cooked to perfection, packed in a freshly toasted seeded burger bun with lettuce and mayonnaise, served with a sauce of your choice.', '🍔', NULL, 1, 1, 2, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('chick-n-bun', 'single', 'On its own', 5.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('chick-n-bun', 'meal', 'Make it a meal', 8.48, 'Adds fries and a drink (+£2.49)', 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('chick-n-bun', 'sauceChoice', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('chick-n-bun', 'mealDrink', 1) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('chick-n-bun', 'extraDips', 2) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('crispy-crunch', 'chicken-burgers', 'The Crispy Crunch', 'Freshly fried battered chicken fillet with lettuce and your choice of chilli sauce or mayonnaise, served in a freshly toasted seeded burger bun.', '🍔', NULL, 1, 1, 3, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('crispy-crunch', 'single', 'On its own', 5.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('crispy-crunch', 'meal', 'Make it a meal', 8.48, 'Adds fries and a drink (+£2.49)', 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('crispy-crunch', 'crispySauce', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('crispy-crunch', 'mealDrink', 1) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('crispy-crunch', 'extraDips', 2) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('triple-threat', 'club-sandwich', 'Triple Threat', 'Marinated chicken chunks and seasoned vegetables in freshly toasted bread, served with coleslaw and your choice of sauce.', '🥪', NULL, 1, 1, 4, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('triple-threat', 'single', 'On its own', 6.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('triple-threat', 'meal', 'Make it a meal', 9.48, 'Adds fries and a drink (+£2.49)', 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('triple-threat', 'sauceChoice', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('triple-threat', 'mealDrink', 1) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('triple-threat', 'extraDips', 2) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('foggy-bbq', 'club-sandwich', 'Foggy BBQ', 'Marinated chicken chunks in special BBQ sauce with seasoned vegetables, served in toasted bread with coleslaw and your choice of sauce.', '🥪', NULL, 0, 1, 5, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('foggy-bbq', 'single', 'On its own', 6.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('foggy-bbq', 'meal', 'Make it a meal', 9.48, 'Adds fries and a drink (+£2.49)', 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('foggy-bbq', 'sauceChoice', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('foggy-bbq', 'mealDrink', 1) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('foggy-bbq', 'extraDips', 2) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('cheesy-rascal', 'cheesy-rascal', 'Cheesy Rascal', 'Freshly fried fries loaded with marinated chicken chunks, pizza sauce, jalapenos, capsicum, and topped with mozzarella cheese, mayonnaise and chilli garlic.', '🧀', NULL, 1, 1, 6, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('cheesy-rascal', 'std', 'Serve', 6.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('cheesy-rascal', 'extraDips', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('chilli-cheese-bites', 'add-ons', 'Chilli Cheese Bites', NULL, '🧀', NULL, 0, 1, 7, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('chilli-cheese-bites', 'std', '5 pcs', 3.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('chilli-cheese-bites', 'extraDips', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('mozzarella-sticks', 'add-ons', 'Mozzarella Sticks', NULL, '🧀', NULL, 0, 1, 8, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('mozzarella-sticks', 'std', '4 pcs', 1.49, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('mozzarella-sticks', 'extraDips', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('coleslaw', 'add-ons', 'Coleslaw', NULL, '🥗', NULL, 0, 1, 9, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('coleslaw', 'std', 'Serve', 1.29, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('dips-peri-salt', 'add-ons', 'Dips & Peri Salt', NULL, '🥣', NULL, 0, 1, 10, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('dips-peri-salt', 'std', 'Serve', 0.50, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('dips-peri-salt', 'dipType', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('chicken-nuggets', 'kids-meal', 'Chicken Nuggets', NULL, '🍗', NULL, 0, 1, 11, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('chicken-nuggets', '6pc', '6 pcs', 3.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('chicken-nuggets', '8pc', '8 pcs', 4.99, NULL, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('chicken-nuggets', '10pc', '10 pcs', 5.99, NULL, 2) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('chicken-nuggets', 'extraDips', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('chicken-poppers', 'kids-meal', 'Chicken Poppers', NULL, '🍗', NULL, 0, 1, 12, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('chicken-poppers', '6pc', '6 pcs', 3.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('chicken-poppers', '8pc', '8 pcs', 4.99, NULL, 1) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('chicken-poppers', '10pc', '10 pcs', 5.99, NULL, 2) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('chicken-poppers', 'extraDips', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('hash-brown', 'kids-meal', 'Hash Brown', NULL, '🥔', NULL, 0, 1, 13, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('hash-brown', 'std', '4 pcs', 3.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('hash-brown', 'extraDips', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('fries', 'kids-meal', 'Fries', NULL, '🍟', NULL, 1, 1, 14, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('fries', 'std', 'Serve', 2.99, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('fries', 'extraDips', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('soft-drinks', 'beverages', 'Soft Drinks', NULL, '🥤', NULL, 0, 1, 15, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('soft-drinks', 'std', 'Can', 1.29, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO item_modifier_groups (item_id, group_id, display_order) VALUES ('soft-drinks', 'softDrinkChoice', 0) ON DUPLICATE KEY UPDATE display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('water', 'beverages', 'Water', NULL, '💧', NULL, 0, 1, 16, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('water', 'std', 'Bottle', 1.00, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);
INSERT INTO items (id, category_id, name, description, emoji, image_id, is_popular, is_published, display_order, order_types) VALUES ('juice', 'beverages', 'Juice', NULL, '🧃', NULL, 0, 1, 17, NULL) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), description=VALUES(description), emoji=VALUES(emoji), is_popular=VALUES(is_popular), display_order=VALUES(display_order), order_types=VALUES(order_types);
INSERT INTO item_sizes (item_id, size_key, name, price, note, display_order) VALUES ('juice', 'std', 'Bottle', 1.00, NULL, 0) ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), note=VALUES(note), display_order=VALUES(display_order);

-- Trading hours
DELETE FROM shifts;
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (1, 43200, 86340, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (1, 0, 3600, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (2, 43200, 86340, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (2, 0, 3600, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (3, 43200, 86340, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (3, 0, 3600, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (4, 43200, 86340, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (4, 0, 3600, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (5, 43200, 86340, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (5, 0, 7200, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (6, 43200, 86340, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (6, 0, 7200, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (7, 43200, 86340, 0, 0);
INSERT INTO shifts (day_of_week, start_second, end_second, no_delivery, no_pickup) VALUES (7, 0, 7200, 0, 0);

INSERT INTO closed_dates (closed_date, reason) VALUES ('2026-12-25', 'Christmas Day') ON DUPLICATE KEY UPDATE reason=VALUES(reason);
INSERT INTO closed_dates (closed_date, reason) VALUES ('2026-12-26', 'Boxing Day') ON DUPLICATE KEY UPDATE reason=VALUES(reason);

-- Hero banners
INSERT INTO banners (id, title, subtitle, body, button_text, button_href, image_id, background_image_id, display_order, is_published) VALUES ('banner-welcome', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1) ON DUPLICATE KEY UPDATE title=VALUES(title), subtitle=VALUES(subtitle), body=VALUES(body), button_text=VALUES(button_text), display_order=VALUES(display_order);
INSERT INTO banners (id, title, subtitle, body, button_text, button_href, image_id, background_image_id, display_order, is_published) VALUES ('banner-meal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 1) ON DUPLICATE KEY UPDATE title=VALUES(title), subtitle=VALUES(subtitle), body=VALUES(body), button_text=VALUES(button_text), display_order=VALUES(display_order);
INSERT INTO banners (id, title, subtitle, body, button_text, button_href, image_id, background_image_id, display_order, is_published) VALUES ('banner-rascal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 1) ON DUPLICATE KEY UPDATE title=VALUES(title), subtitle=VALUES(subtitle), body=VALUES(body), button_text=VALUES(button_text), display_order=VALUES(display_order);

-- Settings (JSON singletons)
INSERT INTO settings (setting_key, value_json) VALUES ('store_config', '{"name":"Eat On","legalName":"The Food Table Ltd","tagline":"Good Food Good Mood","isHalal":true,"address":"The Howard Centre, Howardsgate, Welwyn Garden City","postcode":"AL8 6HA","city":"Welwyn Garden City","country":"United Kingdom","phoneDisplay":"01707 555142","phone":"+441707555142","email":"orders@eaton.food","timeZone":"Europe/London","currency":"£","currencyCode":"GBP","location":{"lat":51.8014,"lng":-0.2045}}') ON DUPLICATE KEY UPDATE value_json=VALUES(value_json);
INSERT INTO settings (setting_key, value_json) VALUES ('order_setup', '{"isDeliveryOn":true,"isPickupOn":true,"isDineInOn":false,"defaultOrderType":"pickup","deliveryTime":35,"pickupTime":10,"isPreOrderingEnabled":true,"scheduleSlotMinutes":15,"scheduleMaxDaysAhead":2,"useRadiusBasedDeliveryArea":false,"deliveryRadiusKm":5,"deliveryAreaLabel":"Welwyn Garden City, Welwyn and Hatfield","servedPostcodeDistricts":["AL6","AL7","AL8","AL9","AL10"],"deliveryFee":2.49,"isDeliveryFreeOver":true,"freeDeliveryThreshold":25,"minimumDeliveryOrder":12,"isCardPaymentAccepted":true,"isCashPaymentAccepted":false,"isCashPaymentAcceptedDelivery":false,"isPlatformSurchargeLevied":true,"platformSurchargeAmt":0.25,"platformSurchargePercentage":2,"promo":{"isOn":true,"code":"EATON10","title":"10% OFF your FIRST order","message":"Get 10% off your first order over £20","buttonText":"Order now","percentage":10,"minimumSpend":20}}') ON DUPLICATE KEY UPDATE value_json=VALUES(value_json);
INSERT INTO settings (setting_key, value_json) VALUES ('promo', '{"isOn":true,"code":"EATON10","title":"10% OFF your FIRST order","message":"Get 10% off your first order over £20","buttonText":"Order now","percentage":10,"minimumSpend":20}') ON DUPLICATE KEY UPDATE value_json=VALUES(value_json);
INSERT INTO settings (setting_key, value_json) VALUES ('banner_settings', '{"isAutoplayOn":true,"autoplaySeconds":6,"areEmbersOn":true,"emberIntensity":0.4}') ON DUPLICATE KEY UPDATE value_json=VALUES(value_json);
INSERT INTO settings (setting_key, value_json) VALUES ('manual_status', '{"value":"auto"}') ON DUPLICATE KEY UPDATE value_json=VALUES(value_json);

SET FOREIGN_KEY_CHECKS = 1;
